anspress/anspress

- admin/flagged.php
- admin/moderate.php
- includes/actions.php
- includes/badges.php
- includes/class-validation.php
- includes/functions.php
- includes/history.php
- includes/labels.php
@rahularyan requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/wp3/anspress/
> Scrutinizer Auto-Fixes

- widgets/question_stats.php
According to question microformat definintion, there is should be dateModified instead of dateUpdated
Testing with https://developers.google.com/structured-data/testing-tool/ gives one error
> Schema.org dateUpdated -> dateModified

- includes/answer-loop.php
- includes/question-loop.php
https://anspress.io/questions/question/bug-date-not-rendered/
> Schema.org datetime render fixed.

- assets/js/ap-admin.js
- assets/js/common.js
- assets/js/tags.js
on() is basically the same just does not throw notices when jquery migrate 3.0 is active.
> Delegate is depecated in jQuery 3.0

- addons/free/email.php
> Better english, past tense

- Gruntfile.js
- languages/anspress-question-answer-ru_RU.po
- package.json
Big thanks for the plugin!
Where could I report a bug?
P.S. If you would be not satisfied with the whole pull request, I could split it.
> Minor improvements 20170204

- languages/anspress-question-answer-it_IT.po
...i'll add/fix more translations as soon as possible
> Starting italian translation review

- .gitignore
...we should clean the repo from such files too
> ignoring linux backup files

- templates/single-question.php
ap_question_metas() is responsible for echoed string...
> void function ap_question_metas()

- includes/votes.php
Add hints specific to the true voting buttons meaning...
> Be more specific about the voting possibilities

- includes/class-form-hooks.php
Other than this typo, the Update Answer fix works wonderfully!
> For answer_form(), submit_label should be Update Answer

- includes/class-form-hooks.php
Just a missing dot in comment form
> Typo: missing dot

- lib/form/class-editor.php
Please read my commit message !
> I added some code for responding error which would happen on processing image.

- activate.php
just changed category.php -> categor**ies**.php
Check please!
> Fixed small bug

- admin/anspress-admin.php
- ajax/toggle-best-answer.php
- includes/class-form-hooks.php
please see line 546 ~ 548.
Check please.
> more simplify

- templates/addons/category/single-category.php
Allow html in ```single-category.php``` description
_(every once in a while, I remember some php)_
> Allow html in single-category.php description

- includes/functions.php
This code causes a warning, the check is needed
> Added condition for existence of index

- templates/scss/main.scss
remove double @import in main.scss
> remove double @import

- admin/anspress-admin.php
Reason:
I want to display the admin notices only to certain admins.
The filter allows us to remove admin notices via custom code integration
> Add filter to modify AnsPress admin notices

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/feature_request.md
- admin/views/dashboard.php
* Open the **Documents and FAQ** welcome page content link in a new tab/window
> [Fix] Documents and FAQ AnsPress Welcome Page Link Target

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/feature_request.md
- admin/views/dashboard.php
* Fixes the question post date display on all questions on the AnsPress Welcome Page
> [Fix] Welcome Page Questions Date only Displays in the Latest Question only for the same date

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/feature_request.md
- widgets/search.php
> [Fix] PHP warning on (AnsPress) Search widget

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/custom.md
- .github/ISSUE_TEMPLATE/feature_request.md
- widgets/ask-form.php
> [Fix] PHP warning on (AnsPress) Ask form widget

- includes/deprecated.php
- includes/functions.php
Created from PR [#756](https://github.com/anspress/anspress/pull/756)
> Depreacted: ap_reponce_message

- admin/views/dashboard.php
- assets/ap-admin.scss
* Fixes the design of AnsPress Welcome page
> [Fix] Plugin Welcome Page Design

- admin/ajax.php
* Proper addon enabled/disabled message
> [Fix] Features enable and disable reloads the page

- assets/ap-admin.scss
* Fix the options header design when it is on the closed state
> [Fix] Options Page Closed Options Content Design

- admin/views/reputation-events.php
* Notify the users that the **Reputations** options have been saved
> [Fix] Reputations options when saved does not notify the user that the options are updated in any way 

- admin/anspress-admin.php
- assets/js/common.js
* Open the **Theme & Extensions** submenu item link in a new tab/window
> [Fix] Theme & Extensions Submenu Item Link Target

- assets/js/question.js
- templates/functions.php
> Revert "[Fix] Answer editor does not close by itself after answering the question if Quick Tags editor is enabled"

- includes/theme.php
* Fixes PHP warning message being logged to debug file if no AnsPress default pages is set and navigated to plain permalink question page
> [Fix] PHP Warning: Undefined array key 0 

- includes/shortcode-basepage.php
- lib/class-form.php
* Removes unrequired enqueue of **anspress-main** and **anspress-upload** scripts
> [Fix] Unrequired enqueue of custom JS files

- includes/post-types.php
* Fixes the post updated and bulk post updated messages for **Question** and **Answer** custom post type
> [Fix] Post updated and bulk post updated messages

- includes/theme.php
- templates/functions.php
* Fixes localization of scripts causing JS issue when **Load assets in AnsPress page only?** option is enabled
> [Fix] jQuery error if Load assets in AnsPress page only? option is enabled

- includes/qaquery-hooks.php
- includes/theme.php
* Adds the **Solved** order by option on the Questions **Order by** filter
> [Fix] Questions Order by filter Solved filter option 

- addons/notifications/notifications.php
- includes/functions.php
* Fixes notification marked as seen gets displayed in the **Unseen** notification link as well
> [Fix] Notifications unseen filter shows the seen notifications

- assets/js/common.js
* Fixes the notifications available not being shown if the user clicks on the answer form first and later on the notification icon at the top header when viewing the questions page
> [Fix] Uncaught TypeError: jQuery.apParseParams is not a function

- admin/anspress-admin.php
- includes/hooks.php
- includes/options.php
* Added an option to disable the admin bar for non-administrative users
> [Fix] Hide the Admin Bar

- widgets/breadcrumbs.php
* Fixes the single question page breadcrumb trail not displaying the last trail item
> [Fix] Single question page breadcrumb trail does not display the last trail item

- includes/post-types.php
* Enable the permalink slug to be modified via question edit page from the WordPress dashboard
> [Fix] Allow editing question slug in wp-admin

- addons/categories/categories.php
- addons/tags/tags.php
- includes/post-types.php
- includes/rewrite.php
* Fixes the URL structure rewrites for use with the Polylang plugin
> [Fix] Recheck AnsPress with Polylang

- includes/hooks.php
- widgets/breadcrumbs.php
* Fixes the **Ask a Question** page and **Activities** page breadcrumb trail not displaying the last trail item
> [Fix] Ask a Question page and Activities page breadcrumb trail does not display the last trail item

- admin/views/dashboard.php
* Fixes the proper **All looks fine** message display on the **Require Attention** post box on the **AnsPress** welcome page
> [Fix] All looks fine gets displayed even though there is a flagged and moderate answer available

- admin/views/options.php
* Fixes the official links of ours to the Facebook and Twitter social sites
> [Fix] Social links on the settings page

- assets/ap-admin.scss
* Fixes the responsive design for the **New Answer** page
> [Fix] New Answer page is not responsive

- assets/ap-admin.scss
* Fixes the responsiveness of the **AnsPress** options/settings page
> [Fix] AnsPress options page is not responsive

- includes/votes.php
* Better hover title for the **Up vote this post** and **Down vote this post** to render the respective Question or Answer post type label instead of showing post
> [Fix] Up vote and Down vote title
