anspress/anspress

includes/class-form.php
Hi, great plugin. I was getting this notice:
Notice: Undefined index: name in .../wp-content/plugins/anspress-question-answer/includes/class-form.php on line 459
and that is how I fixed it. Server is running with PHP 5.6.9
=> Fix notice

activate.php
The activation hook uses a database table creation script that references $wpdb->base_prefix, which on multisite is the prefix for the primary site. The rest of the code uses $wpdb->prefix, which is correct for multisite. If you install AnsPress on a multisite subsite, the table reference breaks because the table was created with the wrong prefix. This pull request fixes that problem.
=> Fixed compatibility issue with multisite subsites

includes/hooks.php
Updates the avatar size from 80px to 20px. Which is the correct size (20px is also used in the anspress css). 
When using the 80px the avatar is not correctly sized in the menu. This resolves this issue.
=> Update hooks.php for better avatar

includes/question-loop.php
We should be able to redefine ap_get_questions for different situations. For example, if you'd like to hide a category or a question belonging to a category based on a role, you should be able to do that without affecting the main plugin by redefining your ap_get_questions.
=> Made ap_get_questions overridable.

includes/users-loop.php
The function ap_user_get_member_for() previously gave no output for users who joined today.
Changed to:
If member has been registered for over 1 hour but under 1 day, output will be "_ hours".
If a member has been registered for under 1 hour, output will be "_ minutes".
=> Improved accuracy of 'member for _'.

includes/bp.php, includes/subscriber.php
For now BP notification for new answer or comment are working well. Also removing/trashing question, answer or comment will remove notification as well. 
todo: mark bp notification as read after user reads answer or comment (after user clicks bp notification url and will be redirected to that post or loads post corresponding to that notification).
Need a way to trigger function after question page is loaded and also it should return post ids or single post id. Hooking to the the_post action is overkill, and will trigger function on every post from entire site. So maybe modification of question/answer loop is in order or a additional parameters added to the notification link?
=> fix for BP notify (add or remove) for new answer and comment

addons/free/category.php
_x() must be used with a context (for translators). If no context is provided, it's better (and more efficient) to use __()
=> Make some strings translatable without context

addons/free/profile.php
The function doesn’t return $posts, meaning that no other plugins can
use the hook posts_pre_query
=> Correcting modify_query_archive

includes/class-theme.php
According to https://developer.wordpress.org/themes/template-files-section/page-template-files/, singular.php is one of the default templates.
=> Add singular.php as one of the default templates

includes/hooks.php
the comment_id is not stocked in the activity and returned with a value
of 0. Wordpress then throw an error in the activity feed when trying to
get the comment_excerpt of a comment with ID of 0
=> activity feed broken for editing comment

templates/scss/form.scss
Constraints textarea to fill 100% of the width parent, add a bottom margin like other controls.
=>  Better textarea rendering

includes/activity.php
Otherwise, the ap_q param will always get a zero value.
=> Use q_id for the ap_q param.

admin/anspress-admin.php
If I click 'new Question' in admin page, the 'All Question' is highlighted. And If I click Tags in Anspress the 'Posts > Tags' is highlighted. So I fixed this minor problems.
=> Fixed submenu highlight in 'new Question' and 'Tags'

includes/functions.php
I am using BuddyPress 3.1.0 and Anspress 4.1.14.
Accessing Q&A tab bp_current_component returns "qa".
=> Return true when bp_current_component returns "qa"

lib/class-validate.php
newline fix in case of \r\n\r\n sequences in post content
anspress is currently removing required newlines which leads to br tags instead of p tags
This fix handles this and keeps double newlines to get p in the output.
Can be tested the following way:
1. Create a post with newlines. 
2. The output is br tags in a p tag which is wrong. Only tripple newlines generates p tags.
3. Editing the post removes newlines and at the end you will get br tags instead of the desired p tags.
=> newline fix in case of \r\n\r\n sequences in post content

admin/anspress-admin.php
Two fields under Posts & Comments had the same labels...one should be "Minimum question content", the other should be "Minimum answer content".
=>  Corrected label in Admin Options

includes/functions.php
Hi, when user data is cached without user_pass field, then login not work, because cant handle hash comparsion when get_user_by() so field 'user_pass' must be added to the ap_post_author_pre_fetch() function. Or why just not use build-in cache_users($ids); function?
=> Fix for cached password missing login bug

includes/functions.php, languages/anspress-question-answer.pot
Fixing an issue that prevents the translation of human time string: `%s ago`. The problem was due to the wrong usage of `_x()` function. It can be easily resolved by using the proper function and updating the translation files.
=> Fix human time translation. #519

templates/scss/reset.scss
This is a horrible style and should never be in any plugin. These breaks bootstrap buttons and many other things. It makes every visited link have no colors. Not sure if this way a mistake but its way to specific for a plugin.
=> Remove bad style

addons/tags/tags.php
Fixed invalid/unsupported argument type (string) passed to `count` function. This fixes #772
=> [Fix] Tags addon - unsupported argument passed to count function

widgets/ask-form.php
=> [Fix] PHP warning on (AnsPress) Ask form widget

addons/categories/widget.php
* Fixes PHP warning message for undefined array key hide_empty when using this widget initially
* Fixes PHP warning message for undefined array key parent when using this widget initially
* Fixes PHP warning message for undefined array key number when using this widget initially
* Fixes PHP warning message for undefined array key orderby when using this widget initially
* Fixes PHP warning message for undefined array key order when using this widget initially
=> [Fix] PHP warning on (AnsPress) Categories widget

admin/anspress-admin.php
* Fixes the double **Multiple Answers** option available inside the User Access Control option section
=> [Fix] Double Multiple answers options in the User Access Control option section

includes/theme.php
* Fixes the PHP warning message being logged into the **debug.log** file when viewing the custom menu management page if AnsPress default pages are not being set as required
=> [Fix] PHP warning on the menu edit page

includes/class-form-hooks.php
* **Answer editor?** plugin option does not render the **Quick tags editor** in the front end even though it is enabled from the plugin options page
=> [Fix] Quick tags editor does not work when enabled for Answer editor? plugin option

admin/views/select_question.php
* Fixes extra > after the question title in the **New Answer** page
=> [Fix] Extra > added after the title in New Answer page

includes/class-form-hooks.php, templates/login-signup.php
* Fixes the user registration done on posting a question or an answer even though WordPress **Membership** option is disabled
=> [Fix] User registration is done even though WordPress Membership option is disabled

addons/avatar/avatar.php
* Adds **Clear avatar cache** button does not clear the Avatar cache until the user/admin user clicks on the confirm button to clear the avatar cache from their site
=> [Fix] Clear avatar cache does not have confirm option before deleting the Avatar cache

widgets/search.php
=>  [Fix] PHP warning on (AnsPress) Search widget

admin/views/options.php
* Fixes the PHP warning message when pages option is saved with page selected as Select an option
=> [Fix] PHP warning on Pages option save when page selected is Select an option

admin/views/dashboard.php
* Fixes the display of the answers in the Latest Answers section of the AnsPress Welcome Page
* Fixes the post date display for all answers listed in the Latest Answers section of the AnsPress Welcome Page
=> [Fix] Welcome Page Answers Section Empty

admin/views/toggle-features.php
* Proper display of the active features list in the plugin Features option
=> [Fix] Features enabled active section not proper for some cases

assets/js/common.js, includes/ajax-hooks.php, includes/theme.php
* Display the question title for the question subscription/unsubscription by the user via Ajax message as well
* Fixes the display of the subscription count for the question via Ajax event on clicking the **Subscribe** or **Unsubscribe** to question button
=> [Fix] Subscribed/Unsubscribed to the Question Ajax message

admin/anspress-admin.php, assets/js/common.js
* Fixes the page reload issue for the **Select All** button link in the custom menu management page regarding AnsPress plugin's pages
=> [Fix] Select all menu items created via AnsPress plugin reloads the custom menu management page

addons/categories/categories.php
* Fixes PHP warning being logged to error log file if **Question Categories** specific category has set either **Category icon class** or **Category icon color** but not **Image** option
=> [Fix] PHP Warning: Undefined array key image

addons/profile/profile.php
* Fixes the **Load more answers** not hiding issue on the User Profile page Answers' tab even though all answers from the user is already loaded
=> [Fix] User profile page Answers tab Load more answers button does not hide even though all answers provided by the user is already loaded

includes/common-pages.php
* Fixes PHP fatal error for exclude roles case when selected any on of them available previously and later unselected/deselected all of them
=> [Fix] Fatal error: Uncaught Error: array_keys(): Argument #1 ($array) must be of type array

includes/qaquery.php
* Fixes PHP Warning: Attempt to read property "answers" on bool when viewing non question page
* Fixes PHP Warning: Attempt to read property "post_modified_gmt" on bool when viewing non question page
=> [Fix] PHP warning message when using (AnsPress) Question Stats widget

admin/anspress-admin.php
* Fixes the total number of attention required for the **AnsPress** main menu item in the back end when a Question or an Answer is flagged by the user
=> [Fix] When a Question or an Answer is flagged then, in AnsPress main menu item, double the number shows as total count number required attention

addons/notifications/notifications.php, admin/ajax.php, admin/license.php, admin/views/roles.php, includes/ajax-hooks.php, includes/comments.php, includes/common-pages.php, includes/deprecated.php, includes/flag.php, includes/functions.php, includes/post-status.php, includes/upload.php, includes/votes.php
* Check for function exists before defining `ap_verify_nonce` function
=>  [Fix] Function name collision with Actions Pack Plugin

includes/class-theme.php, includes/functions.php, includes/hooks.php
* Fixes to prefix question document title with **[Solved]** if **Show solved prefix** option is enabled
=> [Fix] Show solved prefix plugin option not adding the [Solved] prefix before the question title

lib/form/class-select.php
* Fixes the ask form category order option modifying the display order of category select option in the ask form
=> [Fix] Ask form category order plugin option not working

includes/class/roles-cap.php
* Fixes the **OP can answer?** plugin option working in opposite way
=> [Fix] OP can answer? plugin option is working in opposite way

activate.php
* Fixes PHP error(warning) messages being logged into debug log file if WordPress debug log is enabled and plugin is activated for the first time
=> [Fix] Plugin activate on fresh WordPress install generates PHP error(warning) messages

includes/post-status.php
* Modify the Ajax message for post status change on Question and Answer post type from the front end
=> [Fix] Post status updated successfully Ajax message on question and answer status changes

includes/flag.php
* Modify the Ajax message for flagging either a question or an answer by the logged in user from the front end
=> [Fix] Flagged question and answer Ajax message

includes/ajax-hooks.php, includes/flag.php, includes/theme.php
* Modify the post action links title for **Flag this post**, **Delete this post (can be restored again)**, and **Delete post permanently (cannot be restored again)** to render the respective Question or Answer post type label instead of showing post
=> [Fix] Question and Answer action links title

activate.php
* Fixes default features(addons) enabled automatically on plugin activation although already disabled by the user
=> [Fix] Default plugin features(addons) activated automatically on plugin activation

assets/js/question.js
* Fix the answer editor does not close by itself after answering the question if Quick Tags editor is enabled
* Remove unrequired **console.log** for rendering the form field when clicking on the answer editor
=> [Fix] Answer editor does not close by itself after answering the question if Quick Tags editor is enabled

addons/email/class-helper.php, addons/email/email.php, admin/views/emails.php, includes/functions.php
* Fix the **{site_name}**, **{site_url}**, and **{site_description}** smart tags for email delivery change to required contents for **New Question**, **New Answer**, and **New Comment** email templates
* Fix the **{answer_excerpt}** smart tags for email delivery change to required contents for **Edit Answer** email templates
* Fix the **More email options** link available in the **Email Templates** option
=> [Fix] Some of the allowed tags is not working on email notifications set via Email Templates options

templates/addons/notification/index.php
* Fixes the **Mark all as seen** button display on notification page on the required notifications tab/links only
=> [Fix] Notifications page Seen filter displays the Mark all as seen button

addons/notifications/notifications.php
* Fixes PHP warning message being logged into the debug log file when notification addon is enabled and adding answer to a question from back end if WordPress debug log is enabled
=> [Fix] Warning: Attempt to read property post_author on null

addons/categories/categories.php
* Modifies the **Font icon class, if image not set** string to include url to the icon classes which can be used
* Fixes **Category icon color** title and description on question category edit page
=> [Fix] Improper description for Font icon class, if image not set category option

addons/buddypress/buddypress.php
* Fix - PHP Deprecated: Required parameter $component_action_name follows optional parameter $format in /var/www/html/wp-content/plugins/anspress/addons/buddypress/buddypress.php on line 431
* Fix - PHP Deprecated: Required parameter $component_name follows optional parameter $format in /var/www/html/wp-content/plugins/anspress/addons/buddypress/buddypress.php on line 431
* Fix - PHP Deprecated: Required parameter $id follows optional parameter $format in /var/www/html/wp-content/plugins/anspress/addons/buddypress/buddypress.php on line 431
=> [Fix] PHP Deprecated message regarding BuddyPress addon

templates/activities/activities.php, templates/scss/activity.scss
* Fixes the empty border display on the activities page if there are no user activities found
=> [Fix] Empty border on the activities page if there are no user activities found

admin/anspress-admin.php, admin/views/options.php
* Fixes the **Max upload size** plugin option value to not exceed the value set in **max_upload_size php.ini** configuration file
=> [Fix] Max upload size plugin option can exceed the value to be set inside it more than max_upload_size php.ini settings

addons/tags/tags.php, includes/taxo.php
* PHP warning to be logged into debug log file if **(AnsPress) Breadcrumbs** widget is used in the **(AnsPress) Question List** Top widgetized area and viewing the individual tag page
* Fixes the display of the single tag item in the single tag page and Tags item in the tags archive page for the **(AnsPress) Breadcrumbs** widget
* Fixes the condition to check for currently viewing page is either a tag page or tags archive page
=> [Fix] Attempt to read property name on bool

addons/syntaxhighlighter/script.js, assets/js/common.js, templates/functions.php
* Fixes the **Syntax Highlighter** addon/feature not working when Quick tags editor is enabled for Question and Answer
=> [Fix] Syntax Highlighter addon is not working when Quick tags editor is enabled 

includes/class-theme.php
* Fixes block based theme with empty **index.php** file does not display any AnsPress page contents on the front end when viewing the AnsPress related page
=> [Fix] Blank contents on AnsPress related pages if Block theme is used

includes/functions.php
* Fixes the TinyMCE editor to load when Jetpack CDN option of **Speed up static file load times** is enabled when the user is trying to answer the question
=> [Fix] TinyMCE editor fails to load when WordPress Jetpack CDN option "Speed up static file load times" is enabled

assets/js/notifications.js
* Fixes the **Mark all as seen** notification button click Ajax event to reset the notification counter number throughout the site
=> [Fix] Mark all as seen notification button click does not reset the notification counter number

lib/form/class-editor.php
* Fixes the **Insert image** button on the question and answer editor to not get displayed if **Allow image upload** option is disabled
=> [Fix] Insert image button on Question and Answer form always available

includes/hooks.php, includes/rewrite.php
* Fixes the questions lists pagination on homepage for **AskBug** theme when the **Your homepage displays** option is set to **Your latest posts**
=> [Fix] Homepage questions pagination does not work directly if the home page is set to Your latest posts

includes/functions.php
* Fixes the breadcrumb trail link to follow the page link set under the plugin **Pages** option
=> [Fix] Breadcrumb trail link does not follow the link to the page set within plugin Pages options

includes/ajax-hooks.php, includes/class/class-activity-helper.php
* Fixes **Marked as closed** question activity still shown after the question content even after the question is re-opened
=> [Fix] Marked as closed question activity always shown even when reverted back

includes/ajax-hooks.php, includes/class/class-activity-helper.php
* Fixes **Marked as featured question** question activity still shown after the question content even after the question is unfeatured
=> [Fix] Marked as featured question question activity always shown even when reverted back

addons/buddypress/buddypress.php, templates/buddypress/question-item.php
* Comments on question and answer is now logged to the BuddyPress activity
* Fixes unrequired number display after answers number on the Users' Questions page, when viewing the user profile Questions' page via the BuddyPress addon enabled
=> [Fix] [BuddyPress Integration] Comments to answers not displayed in activity?

addons/buddypress/buddypress.php
* Fixes PHP Warning: Attempt to read property comment_ID on int when deleting question, answer, or comment from the front end if **BuddyPress** plugin and **BuddyPress** feature/addon is active
=> [Fix] PHP Warning: Attempt to read property "comment_ID" on int

admin/views/select_question.php, includes/qaquery.php
* Fixes the trashed question to not appear on the **Recently active questions** section under the **New Answer** page
=> [Fix] Trashed Question Available On The New Answer Page

templates/scss/category.scss
* Fixes the category icon to be placed exactly in the center of the div on the categories page
=> [Fix] Categories page the category icon is not placed exactly in the center 

includes/hooks.php
* Fixes the answer not deleted automatically with question permanently delete if its post status is other than the publish
=> [Fix] When deleting a question, only the answers with publish status will get deleted

includes/comments.php
* Fixes PHP Warning:  Attempt to read property "comment_post_ID" on null in /var/www/html/wp-content/plugins/anspress/includes/comments.php on line 56
* Fixes PHP Warning:  Attempt to read property "post_type" on bool in /var/www/html/wp-content/plugins/anspress/includes/comments.php on line 77
=> [Fix] PHP warning message when viewing the invalid comment via popup

activate.php, addons/reputation/reputation.php, anspress-question-answer.php, includes/reputation.php
* Fixes the reputation events icon not being displayed inside the circular area on the users' reputation page
=>  [Fix] Reputation events icon not displayed on the users' reputation page
